num = input('Digite um valor')
print('O tipo primitivo desse valor é', type(num))
print('Só possui espaços?', num.isspace())
print('É um número?', num.isnumeric())
print('É alfabetico?', num.isalpha())
print('É Alphanumerico?', num.isalnum())
print('É Maiúscula?', num.isupper())
print('É Minuscula?', num.islower())
print('É Capitalizada?', num.istitle())